"""M1.2: generate seeded per-patient chart plans + draft hidden evidence map.

Outputs (all hidden / generator-only):
  data/_generation/plans/GLP1-xxx.json
  ground_truth/evidence_map.json
  reports/plan_summary.md
"""
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "engine"))
from pa_bench.generation.plan import build_plan  # noqa: E402
from pa_bench.generation.scenarios import DOC_STATES, MED_SCENARIOS  # noqa: E402

RANGES = {"conditions": (3, 8), "observations": (10, 20), "medications": (3, 10), "encounters": (5, 12), "notes": (10, 20)}


def main() -> int:
    spec = json.loads((ROOT / "data/cohort/patients.json").read_text())
    out = ROOT / "data/_generation/plans"
    out.mkdir(parents=True, exist_ok=True)
    all_anns, rows, problems = [], [], []
    for p in spec["patients"]:
        plan, anns = build_plan(p)
        (out / f"{p['patient_id']}.json").write_text(json.dumps(plan, indent=2))
        all_anns += anns
        counts = {k: len(plan[k]) for k in RANGES}
        med_count = sum(1 for m in plan["medications"] if m["resourceType"] in ("MedicationRequest", "MedicationStatement"))
        counts["medications"] = med_count
        for k, (lo, hi) in RANGES.items():
            if not lo <= counts[k] <= hi:
                exempt = k == "medications" and p["clinical_truth"]["medication_scenario"] == "med_list_absent"
                problems.append(f"{p['patient_id']} {k}={counts[k]} outside {lo}-{hi}" + (" (by design)" if exempt else ""))
        rows.append((p, counts, plan, anns))

    # plan-level annotations; merged with note-text scans into ground_truth/evidence_map.json by build_evidence_map.py
    pa = ROOT / "data/_generation/plan_annotations.json"
    pa.write_text(json.dumps({"warning": "EVALUATION ONLY — never send to models", "cohort_id": spec["cohort_id"],
                              "annotations": all_anns}, indent=2))

    lines = ["# Chart plan summary (M1.2)\n", "Generated by `scripts/generate_plans.py` (seeded, deterministic). Hidden artifact.\n",
             "| Patient | Class | Documentation state | Med scenario | Cond | Obs | Meds | Enc | Notes (relevant / distractor / trap) |",
             "|---|---|---|---|---|---|---|---|---|"]
    for p, c, plan, anns in rows:
        rel = sum(1 for n in plan["notes"] if n["role"] != "distractor")
        dis = sum(1 for n in plan["notes"] if n["role"] == "distractor")
        trap = sum(1 for n in plan["notes"] if n["trap"])
        lines.append(f"| {p['patient_id']} | {p['benchmark_design']['class']} | {p['clinical_truth']['weight_management']['documentation_state']} | "
                     f"{p['clinical_truth']['medication_scenario']} | {c['conditions']} | {c['observations']} | {c['medications']} | "
                     f"{c['encounters']} | {c['notes']} ({rel}/{dis}/{trap}) |")
    lines += ["\n## Scenario table\n", "| documentation_state | intended pattern |", "|---|---|"]
    lines += [f"| {k} | {v} |" for k, v in DOC_STATES.items()]
    lines += ["\n| medication_scenario | intended pattern |", "|---|---|"]
    lines += [f"| {k} | {v} |" for k, v in MED_SCENARIOS.items()]
    stance = Counter((a["criterion_id"], a["stance"]) for a in all_anns if a["relevance"])
    lines += ["\n## Annotation counts (relevant)\n", "| concept | SUPPORTS | CONTRADICTS | AMBIGUOUS | NEUTRAL |", "|---|---|---|---|---|"]
    for concept in sorted({k[0] for k in stance}):
        lines.append(f"| {concept} | " + " | ".join(str(stance.get((concept, s), 0)) for s in ("SUPPORTS", "CONTRADICTS", "AMBIGUOUS", "NEUTRAL")) + " |")
    lines.append(f"\nHard-negative (trap) annotations: {sum(1 for a in all_anns if not a['relevance'])}")
    if problems:
        lines += ["\n## Range exceptions\n"] + [f"- {x}" for x in problems]
    (ROOT / "reports/plan_summary.md").write_text("\n".join(lines) + "\n")

    print(f"plans: {len(rows)}  annotations: {len(all_anns)}")
    for x in problems:
        print("RANGE", x)
    hard_fail = [x for x in problems if "(by design)" not in x]
    print("RESULT:", "FAIL" if hard_fail else "PASS")
    return 1 if hard_fail else 0


if __name__ == "__main__":
    sys.exit(main())
